# Generated by Django 5.0.6 on 2025-06-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio (USD)')),
                ('duracion', models.PositiveIntegerField(verbose_name='Duración (horas)')),
                ('nivel', models.CharField(choices=[('INIC', 'Principiante'), ('INT', 'Intermedio'), ('ADV', 'Avanzado')], default='INIC', max_length=10, verbose_name='Nivel')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagen del curso')),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'ordering': ['fecha_creado'],
            },
        ),
    ]
